export type { VisualizerDimensions } from '@/visualizer/dimensions'
export { defaultDimensions } from '@/visualizer/dimensions'
export type { BarVisualState, VisualSemantics } from '@/visualizer/renderModel'
export { defaultVisualSemantics, mapStepToBarStates, resolveVisualState } from '@/visualizer/renderModel'
export type { RenderDimensions, BarDescriptor, RenderFrame, RenderTransition } from '@/visualizer/barRenderer'
export { createBarDescriptors, renderBarsFrame } from '@/visualizer/barRenderer'
export type { CanvasSurface, SurfaceDimensions } from '@/visualizer/canvasSurface'
export { configureCanvasSurface, getPixelRatio, getResponsiveDimensions } from '@/visualizer/canvasSurface'
export type { PlaybackState, PlaybackController } from '@/visualizer/playback'
export { createPlaybackController } from '@/visualizer/playback'
